###############################################################################
#
# ESPHome configuration for the LilyGO TTGO T-Higrow ESP32 plant sensor.
#
# Note: some T-Higrow models have a DHT11 temperature and humidity sensor,
# while others have a BME280 barometer pressure, temperature and humidity
# sensor. This config is for the BME280 model.
#
###############################################################################

esphome:
  name: plantsensor
  platform: ESP32
  board: lolin_d32

logger:
  level: debug

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable over-the-air firmware updates
ota:
  password: "password"

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

# Pull pin 4 high to enable sensor power
switch:
  - platform: gpio
    pin: GPIO4
    name: "Sensor Power"
    id: spower
    restore_mode: ALWAYS_ON
    internal: true
    # Enable spower before i2c
    setup_priority: 1100

i2c:
  sda: 25
  scl: 26
  scan: True

sensor:
  - platform: bme280
    temperature:
      name: "Temperature"
      oversampling: 16x
    pressure:
      name: "Pressure"
    humidity:
      name: "Humidity"
    address: 0x77
    update_interval: 60s
    # Enable after i2c
    setup_priority: 100

  - platform: bh1750
    name: "Illuminance"
    address: 0x23
    update_interval: 60s
    # Enable after i2c
    setup_priority: 100

  - platform: adc
    pin: GPIO32
    name: "Soil"
    update_interval: 60s
    unit_of_measurement: '%'
    accuracy_decimals: 1
    #raw: true
    attenuation: 11db
    filters:
      - calibrate_linear:
        - 2.77 -> 0.0
        - 1.35 -> 100.0
    # Air:            1.85V @ 6db*   2.77V @ 11db
    # Very dry soil:  1.85V @ 6db*   2.76V @ 11db
    # Wet soil:       1.78V @ 6db    1.53V @ 11db
    # Very wet soil:  1.35V @ 6db    1.35V @ 11db
    # Water:          1.37V @ 6db    1.39V @ 11db
    # *Out of range

  # - platform: adc
  #   pin: GPIO34
  #   name: "Salt"
  #   update_interval: 60s
  #   unit_of_measurement: '%'
  #   accuracy_decimals: 1
  #   attenuation: 11db
  #   filters:
  #     - calibrate_linear:
  #       - 2.12 -> 100.0
  #       - 0.14 -> 0.0
  #   # Air:            0.14V @ 11db
  #   # Very dry soil:  0.14V @ 11db
  #   # Wet soil:       1.90V @ 11db
  #   # Very wet soil:  2.12V @ 11db
  #   # Water:          1.63V @ 11db
  #   # *Out of range

  - platform: adc
    pin: GPIO33
    name: "Battery"
    unit_of_measurement: 'V'
    update_interval: 3s
    attenuation: 11db
    raw: true
    filters:
      - calibrate_linear:
        - 0 -> 0.0
        - 4095 -> 7.26 # = 6.6 * 1.1
        
